# DevCell Taskfile. See README.md
version: '3'

vars:
  PORT: '{{.PORT | default "9090"}}'
  HTTP_HOST: '{{.HTTP_HOST | default "0.0.0.0"}}'
  DOCKER_ARGS: '{{.DOCKER_ARGS }}'

  DOCKERFILE: "Dockerfile-local"
  IMAGE_TAG: "latest-local"

  APP_NAME: '{{base .USER_WORKING_DIR}}-{{env "TMUX_PANE" | replace "%" "" | default "0"}}'
  WORKSPACE: "{{.APP_NAME}}"
  BINARY_NAME: "{{.APP_NAME}}"

  DEVCELL_DIR: '{{env "DEVCELL_DIR" | default (printf "%s/dev/dimmkirr/devcell" .HOME)}}'
  COMPOSE: 'docker compose -f {{.DEVCELL_DIR}}/compose.yml $(test -f {{.DEVCELL_DIR}}/compose.local.yml && echo "-f {{.DEVCELL_DIR}}/compose.local.yml")'

  RUN: "{{.COMPOSE}} run --service-ports --name cell-{{.APP_NAME}}-run --remove-orphans {{.DOCKER_ARGS}} -it cell"
  CLAUDE: "{{.RUN}} claude --dangerously-skip-permissions"
  CODEX: "{{.RUN}} codex --dangerously-bypass-approvals-and-sandbox --oss -p lms"
  OPENCODE: "{{.RUN}} opencode --dangerously-bypass-approvals-and-sandbox"
  SHELL: "{{.RUN}} bash"

  CELL_HOME: '{{.HOME}}/.devcell/{{ env "TMUX_SESSION_NAME" | default "sandbox"}}'
  PORT_PREFIX: '{{env "TMUX_PANE" | replace "%" "" | default ""}}'
  BASE_DIR: "{{ default .USER_WORKING_DIR }}"

  # Guest VM paths (convert /Users/<host-user>/... to /Users/vagrant/...)
  GUEST_DIR: '{{regexReplaceAll "^/Users/[^/]+" .USER_WORKING_DIR "/Users/vagrant"}}'
  VAGRANT_CLAUDE: 'vagrant ssh -c "cd {{.GUEST_DIR}} && claude --dangerously-skip-permissions {{.CLI_ARGS}}"'
  VAGRANT_SHELL: 'vagrant ssh -- -t "cd {{.GUEST_DIR}} && exec zsh -l"'
  # MACOS_SSH_HOST: "{{.APP_NAME}}.local"  # Use Vagrantfile default

env:
  APP_NAME: "{{.APP_NAME}}"
  BASE_DIR: "{{.BASE_DIR}}"
  DOCKERFILE: "{{.DOCKERFILE}}"
  IMAGE_TAG: "{{.IMAGE_TAG}}"

  PORT_PREFIX: "{{.PORT_PREFIX}}"
  EXT_VNC_PORT: "{{.PORT_PREFIX}}50"

  VAGRANT_CWD: "{{.DEVCELL_DIR}}"

  PORT: "{{.PORT}}"
  BUILDKIT_PROGRESS: plain
  CELL_HOME: "{{.CELL_HOME}}"
  # MACOS_SSH_HOST: "{{.MACOS_SSH_HOST}}"  # Use Vagrantfile default

###
# Include this via:
# includes:
#   claude:
#     taskfile: ~/dev/Taskfile.yml
#     flatten: true

tasks:

  claude:
    desc: Run Claude CLI in the dev container
    silent: true
    deps: [devcell:claude-json:backup]
    cmds:
      - |
        echo "APP_NAME: {{.APP_NAME}}"
        echo "PORT_PREFIX: {{.PORT_PREFIX}}"
        echo "CELL_HOME: {{.CELL_HOME}}"
        echo "DEVCELL_DIR: {{.DEVCELL_DIR}}"

      - "{{.CLAUDE}} {{.CLI_ARGS}}"

  codex:
    desc: Run Codex CLI in the dev container
    silent: true
    cmds:
      - |
        echo "APP_NAME: {{.APP_NAME}}"
        echo "PORT_PREFIX: {{.PORT_PREFIX}}"

      - "{{.CODEX}} {{.CLI_ARGS}}"

  codex:resume:
    desc: Run Codex CLI in the dev container in resume
    silent: true

    cmds:
      - "{{.CODEX}} resume {{.CLI_ARGS}}"

  opencode:
    desc: Run OpenCode CLI in the dev container
    silent: true
    cmds:
      - |
        echo "APP_NAME: {{.APP_NAME}}"
        echo "PORT_PREFIX: {{.PORT_PREFIX}}"

      - "{{.OPENCODE}} {{.CLI_ARGS}}"

  opencode:resume:
    desc: Run OpenCode CLI in the dev container in resume
    silent: true

    cmds:
      - "{{.OPENCODE}} resume {{.CLI_ARGS}}"


  shell:
    desc: Run Claude CLI in the dev container
    silent: true
    cmds:
      - |
        echo "APP_NAME: {{.APP_NAME}}"
      - "{{.SHELL}} {{.CLI_ARGS}}"

  compose:
    desc: Run docker compose commands
    silent: true
    cmds:
      - |
        echo "APP_NAME: {{.APP_NAME}}"
      - "{{.COMPOSE}} {{.CLI_ARGS}}"

  image:build:
    desc: Build images (use -- --no-cache to force full rebuild)
    silent: true
    cmds:
      - echo "Building base image (devcell:latest)..."
      - DOCKERFILE=Dockerfile IMAGE_TAG=latest docker compose -f {{.DEVCELL_DIR}}/compose.yml build {{.CLI_ARGS}}
      - |
        if [ -f "{{.DEVCELL_DIR}}/Dockerfile-local" ]; then
          echo "Building local image (devcell:latest-local)..."
          DOCKERFILE=Dockerfile-local IMAGE_TAG=latest-local docker compose -f {{.DEVCELL_DIR}}/compose.yml build {{.CLI_ARGS}}
        else
          echo "No Dockerfile-local found, skipping local build"
        fi

  vagrant:destroy:
    desc: Destroy
    silent: true
    cmds:
      - |
        echo "APP_NAME: {{.APP_NAME}}"
        echo "DEVCELL_DIR: {{.DEVCELL_DIR}}"

      - vagrant destroy -f

  macos:claude:
    desc: Run Claude CLI in dev vagrant
    silent: true
    deps: [devcell:claude-json:backup]
    var:
      TMUX_PANE: ""
    cmds:
      - |
        echo "APP_NAME: {{.APP_NAME}}"
        echo "GUEST_DIR: {{.GUEST_DIR}}"
        echo "CELL_HOME: {{.CELL_HOME}}"

        # Copy Vagrantfile.local from example if it doesn't exist
        if [ ! -f "{{.DEVCELL_DIR}}/Vagrantfile.local" ]; then
          cp "{{.DEVCELL_DIR}}/Vagrantfile.local-example" "{{.DEVCELL_DIR}}/Vagrantfile.local"
        fi
      - vagrant up --provider=utm --provision
      - "{{.VAGRANT_CLAUDE}}"

  macos:shell:
    desc: Run shell in dev vagrant
    silent: true
    var:
      TMUX_PANE: ""
    cmds:
      - |
        echo "APP_NAME: {{.APP_NAME}}"
        echo "GUEST_DIR: {{.GUEST_DIR}}"
      - "{{.VAGRANT_SHELL}}"

  macos:stop:
    desc: Stop dev vagrant VM
    silent: true
    var:
      TMUX_PANE: ""
    cmds:
      - |
        echo "APP_NAME: {{.APP_NAME}}"
      - vagrant destroy -f

  vagrant:
    desc: vagrant
    silent: true
    cmds:
      - |
        echo "APP_NAME: {{.APP_NAME}}"
      - vagrant {{.CLI_ARGS}}

  vagrant:box:export:
    desc: "Export UTM VM as Vagrant box (usage: task vagrant:box:export -- <boxname> <vm-name>)"
    silent: false
    cmds:
      - |
        set -e
        if [ -z "{{.CLI_ARGS}}" ]; then
          echo "Usage: task vagrant:box:export -- <boxname> <vm-name>"
          echo "Example: task vagrant:box:export -- devcell-macOS26 callnut-60"
          exit 1
        fi

        BOX_NAME=$(echo "{{.CLI_ARGS}}" | awk '{print $1}')
        VM_NAME=$(echo "{{.CLI_ARGS}}" | awk '{print $2}')
        UTM_DIR="$HOME/Library/Containers/com.utmapp.UTM/Data/Documents"

        if [ -z "$BOX_NAME" ] || [ -z "$VM_NAME" ]; then
          echo "Error: Both boxname and vm-name are required"
          echo "Usage: task vagrant:box:export -- <boxname> <vm-name>"
          exit 1
        fi

        if [ ! -d "$UTM_DIR/$VM_NAME.utm" ]; then
          echo "Error: VM not found at $UTM_DIR/$VM_NAME.utm"
          echo "Available VMs:"
          ls -1 "$UTM_DIR"/*.utm 2>/dev/null | xargs -I {} basename {} .utm
          exit 1
        fi

        echo "Exporting VM '$VM_NAME' as box '$BOX_NAME'..."

        # Create temp directory with correct structure
        TEMP_DIR=$(mktemp -d)

        # Create metadata.json
        echo '{"provider":"utm"}' > "$TEMP_DIR/metadata.json"

        # Create embedded Vagrantfile with box defaults
        cat > "$TEMP_DIR/Vagrantfile" <<'VAGRANTFILE'
        Vagrant.configure("2") do |config|
          config.ssh.username = "vagrant"
          config.ssh.host = "vagrant-macos.local"
          config.ssh.port = 22
          config.ssh.insert_key = false

          config.vm.provider :utm do |utm|
            utm.check_guest_additions = false
            utm.skip_directory_share_mode = true
          end
        end
        VAGRANTFILE

        # Copy VM as box.utm (required name for vagrant_utm)
        echo "Copying VM (this may take a while)..."
        cp -R "$UTM_DIR/$VM_NAME.utm" "$TEMP_DIR/box.utm"

        # Create box archive (no utm/ wrapper - vagrant creates the provider folder)
        echo "Creating box archive..."
        tar cvzf ~/$BOX_NAME.box -C "$TEMP_DIR" metadata.json Vagrantfile box.utm

        # Cleanup temp dir
        rm -rf "$TEMP_DIR"

        echo "Adding box to Vagrant..."
        vagrant box add ~/$BOX_NAME.box --name $BOX_NAME --force

        echo ""
        echo "Box exported successfully!"
        echo "Use with: MACOS_BOX=$BOX_NAME task macos:claude"
        echo ""
        vagrant box list
  

  ########################################################################################################################
  devcell:claude-json:backup:
    desc: Backup .claude.json with timestamp, keep last 5
    silent: true
    internal: true
    cmds:
      - mkdir -p "{{.CELL_HOME}}"
      - touch "{{.CELL_HOME}}/.claude.json"
      - |
        BACKUP_FILE="{{.CELL_HOME}}/.claude.json-devcell-$(date +%Y-%m-%dT%H-%M-%S)-backup"
        cp "{{.CELL_HOME}}/.claude.json" "$BACKUP_FILE" 2>/dev/null || true
        ls -t "{{.CELL_HOME}}"/.claude.json-devcell-*-backup 2>/dev/null | tail -n +6 | xargs rm -f 2>/dev/null || true

  devcell:claude-json:restore:
    desc: Restore .claude.json from latest backup
    silent: true
    cmds:
      - |
        LATEST=$(ls -t "{{.CELL_HOME}}"/.claude.json-devcell-*-backup 2>/dev/null | head -1)
        if [ -n "$LATEST" ]; then
          cp "$LATEST" "{{.CELL_HOME}}/.claude.json"
          echo "Restored from: $LATEST"
        else
          echo "No backup found in {{.CELL_HOME}}"
          exit 1
        fi
