# Claude Jail Taskfile. Used to run Claude.
# Actual app-related taskfile must be in Taskfile.yml
version: '3'

vars:
  PORT: '{{.PORT | default "9090"}}'
  HTTP_HOST: '{{.HTTP_HOST | default "0.0.0.0"}}'

  APP_NAME: '{{ .APP_NAME | default (base .USER_WORKING_DIR)}}'
  WORKSPACE: "{{.APP_NAME}}"
  BINARY_NAME: "{{.APP_NAME}}"
  COMPOSE: "docker compose -f {{.USER_WORKING_DIR}}/.devcontainer/compose.dev.yml"
  RUN: "{{.COMPOSE}} run --remove-orphans -it claude"
  CLAUDE: "{{.RUN}} claude --dangerously-skip-permissions"
  SHELL: "{{.RUN}} bash"
  DB_PATH: ./data/{{.APP_NAME}}.db

  BASE_DIR: "{{ default .USER_WORKING_DIR }}"

env:
  APP_NAME: "{{.APP_NAME}}"
  BASE_DIR: "{{.BASE_DIR}}"

  PORT: "{{.PORT}}"

###
# Include this via:
# includes:
#   claude:
#     taskfile: ~/dev/Taskfile.yml
#     flatten: true

tasks:
  claude:
    desc: Run Claude CLI in the dev container
    silent: true
    deps:
      - _generate-all-configs

    cmds:
      - |
        echo "APP_NAME: {{.APP_NAME}}"
      - "{{.CLAUDE}} {{.CLI_ARGS}}"
  
  shell:
    desc: Run Claude CLI in the dev container
    silent: true
    deps:
      - _generate-all-configs

    cmds:
      - |
        echo "APP_NAME: {{.APP_NAME}}"
      - "{{.SHELL}} {{.CLI_ARGS}}"


  deploy:
    silent: true
    cmds:
      - |
        if ! git remote -v | grep -q "dokku-{{.APP_NAME}}"; then
          echo "Error: dokku-{{.APP_NAME}} remote not found"
          echo "Please add the remote with: git remote add dokku-{{.APP_NAME}} dokku@d100.kirr.dev:{{.APP_NAME}}"
          exit 1
        fi
        git commit --allow-empty -am "WIP" && git push dokku-{{.APP_NAME}} $(git branch --show-current):main        


  ########## Generators ##########
  _generate-mcp-config:
    desc: Generate .mcp.json configuration file
    silent: true
    cmds:
      - |
        cat > {{.BASE_DIR}}/.mcp.json << 'EOF'
        {
          "mcpServers": {
            "kitcut-sse": {
              "type": "sse",
              "url": "http://host.docker.internal:9090/sse",
              "headers": {
                "Authorization": "Bearer ${TEST_AUTH_TOKEN}"
              }
            },
            "kitcut-local": {
              "command": "./kitcut/kitcut",
              "env": {
                "DATA_DIR": "./kitcut/data"
              }
            }
          }
        }
        EOF
        echo "Generated {{.BASE_DIR}}/.mcp.json"

  _generate-app-config:
    desc: Generate app.json configuration file
    silent: true
    cmds:
      - |
        cat > {{.BASE_DIR}}/app.json << 'EOF'
        {
          "healthchecks": {
            "web": [
              {
                "type":        "startup",
                "name":        "web check",
                "description": "Checking if the app responds to the /healthz endpoint",
                "path":        "/healthz",
                "attempts": 3
              }
            ]
          }
        }
        EOF
        echo "Generated {{.BASE_DIR}}/app.json"

  _generate-devcontainer-compose:
    desc: Generate .devcontainer/compose.dev.yml file
    silent: true
    cmds:
      - mkdir -p {{.USER_WORKING_DIR}}/.devcontainer
      - |
        cat > {{.USER_WORKING_DIR}}/.devcontainer/compose.dev.yml << 'EOF'
        ---
        services:
          claude:
            build:
              context: .
              dockerfile: {{.ROOT_DIR}}/.devcontainer/Dockerfile
            working_dir: /${BASE_DIR:-app}
            container_name: claude-jail-${APP_NAME:-app}
            volumes:
              # Mount BASE_DIR under the same path
              - ${BASE_DIR}:/${BASE_DIR}

              # Mount the test run directory as workspace
              - ${BASE_DIR}:/${APP_NAME:-app}


              # Mount Claude and host agents
              - ${HOME:-}/.claude-sandbox/:/root/ # Host-based sandbox home dir
              - ${HOME:-}/.claude/agents:/root/.claude/agents:ro # Host-based agents
              - ${HOME:-}/.claude/commands/kitcut:/root/.claude/commands/kitcut:ro # Host-based commands


            environment:
              APP_NAME: ${APP_NAME:-app}
              IS_SANDBOX: 1
              WORKSPACE: /${APP_NAME:-app}
              TEST_AUTH_TOKEN: ${TEST_AUTH_TOKEN}
            command: tail -f /dev/null  # Keep container running
            networks:
              - claude-jail-network

        networks:
          claude-jail-network:
            driver: bridge
        EOF
        echo "Generated {{.ROOT_DIR}}/.devcontainer/compose.dev.yml"

  _generate-devcontainer-dockerfile:
    desc: Generate .devcontainer/Dockerfile
    silent: true
    cmds:
      - mkdir -p {{.ROOT_DIR}}/.devcontainer
      - |
        cat > {{.ROOT_DIR}}/.devcontainer/Dockerfile << 'EOF'
        FROM public.ecr.aws/docker/library/debian:trixie

        # Install system dependencies
        # build-essential is the meta-package that includes gcc, g++, make, libc-dev, etc.
        # binutils-gold adds the gold linker that Go prefers
        RUN apt-get update && apt-get install -y \
            build-essential \
            binutils-gold \
            curl \
            wget \
            git \
            jq \
            tree \
            ripgrep \
            ca-certificates \
            sqlite3 \
            postgresql-client \
            pkg-config \
            procps \
            htop \
            vim \
            zsh \
            expect \
            && rm -rf /var/lib/apt/lists/*

        # Install Go (multi-arch support)
        ENV GO_VERSION=1.24.6
        RUN ARCH=$(dpkg --print-architecture) && \
            curl -LO https://go.dev/dl/go${GO_VERSION}.linux-${ARCH}.tar.gz && \
            tar -C /usr/local -xzf go${GO_VERSION}.linux-${ARCH}.tar.gz && \
            rm go${GO_VERSION}.linux-${ARCH}.tar.gz
        ENV PATH="/usr/local/go/bin:${PATH}"
        ENV GOPATH="/go"
        ENV PATH="${GOPATH}/bin:${PATH}"

        # Install Task (Taskfile)
        RUN sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

        # Install Node.js and npm (for potential frontend tools)
        RUN curl -fsSL https://deb.nodesource.com/setup_24.x | bash - && \
            apt-get install -y nodejs && \
            rm -rf /var/lib/apt/lists/*

        # Install Go development tools
        RUN go install github.com/air-verse/air@latest && \
            go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest && \
            go install golang.org/x/tools/cmd/goimports@latest

        # Install OpenTofu

        RUN \
          curl -fsSL https://get.opentofu.org/opentofu.gpg | tee /etc/apt/keyrings/opentofu.gpg >/dev/null && \
          curl -fsSL https://packages.opentofu.org/opentofu/tofu/gpgkey | gpg --no-tty --batch --dearmor -o /etc/apt/keyrings/opentofu-repo.gpg >/dev/null && \
          chmod a+r /etc/apt/keyrings/opentofu.gpg /etc/apt/keyrings/opentofu-repo.gpg && \        
          echo "deb [signed-by=/etc/apt/keyrings/opentofu.gpg,/etc/apt/keyrings/opentofu-repo.gpg] https://packages.opentofu.org/opentofu/tofu/any/ any main && \
          deb-src [signed-by=/etc/apt/keyrings/opentofu.gpg,/etc/apt/keyrings/opentofu-repo.gpg] https://packages.opentofu.org/opentofu/tofu/any/ any main" | tee /etc/apt/sources.list.d/opentofu.list > /dev/null && \          
          chmod a+r /etc/apt/sources.list.d/opentofu.list && \
          apt-get update && \
          apt-get update && \
          apt-get install -y tofu

        # Install Docker CLI and Docker Compose v2 (optional - for compose:* tasks)
        # Note: Standard tasks (build, start, test) don't require Docker
        RUN apt-get update && \
            apt-get install -y \
            apt-transport-https \
            gnupg \
            lsb-release && \
            
            curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg && \
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null && \

            apt-get update && \
            apt-get install -y docker-ce-cli docker-compose-plugin && \
            rm -rf /var/lib/apt/lists/*


        # Add uv
        COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

        ENV TINI_VERSION v0.19.0
        ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini-arm64 /tini
        RUN chmod +x /tini
        

        # Add kicad
        COPY --from=kitcad/kicad:latest /kicad-cli bin/

        ENV TINI_VERSION v0.19.0
        ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini-arm64 /tini
        RUN chmod +x /tini


        # Install Claude CLI
        RUN \
          npm install -g @anthropic-ai/claude-code
        
        # Set environment variables
        ENV CLAUDE_HOME=/root

        WORKDIR /${APP_NAME}

        
        ENTRYPOINT ["/tini", "--"]

        EOF
        echo "Generated {{.ROOT_DIR}}/.devcontainer/Dockerfile"


  _generate-all-configs:
    desc: Generate all configuration files
    silent: true
    cmds:
      # - task: _generate-mcp-config
      #   vars:
      #     BASE_DIR: "{{.BASE_DIR}}"
      # - task: _generate-app-config
      #   vars:
      #     BASE_DIR: "{{.BASE_DIR}}"
      - task: _generate-devcontainer-compose
        vars:
          BASE_DIR: "{{.ROOT_DIR}}"
      - task: _generate-devcontainer-dockerfile
        vars:
          BASE_DIR: "{{.ROOT_DIR}}"
      - echo "All configuration files generated successfully!"
