package qemu

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
)

// The SSH payload for a file-backed stage is an invocation and nothing else:
// no logic, no interpolation, no Go-built PowerShell. That is the whole
// point of CELL-402 — the interpolation layer is what produced lost quotes,
// a colon parsed as a drive, and two runs lost to quote stripping.
func TestRenderStageInvocation_ResolvesTheVolumeInTheGuest(t *testing.T) {
	got := renderStageInvocation(GuestStage{ScriptFile: "wsl2-enable.ps1"})

	// The drive letter is assigned by Windows and moves between boots
	// (observed D: and E:), so the host cannot know it — the payload must
	// resolve it by marker, in the guest.
	assert.Contains(t, got, GuestLogVolumeMarker, "resolution is by marker file")
	assert.NotRegexp(t, `[A-Z]:\\devcell\\stages`, got, "no hardcoded drive letter")
	assert.Contains(t, got, `\devcell\stages\wsl2-enable.ps1'`)
	assert.Contains(t, got, "throw", "a missing volume must fail loudly, not silently skip")
	// Running a .ps1 FILE is subject to the execution policy; inline
	// -EncodedCommand never was. Run 20260803T083705 died at stage 1 with
	// "running scripts is disabled on this system". Process scope only —
	// the guest's persistent policy is not ours to change.
	assert.Contains(t, got, "Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass -Force",
		"file-backed stages need the policy lifted for this process")
	assert.NotContains(t, got, "-Scope LocalMachine", "never change the guest's persistent policy")
	assert.NotContains(t, got, "function", "no logic may be generated by Go")
}

// Arguments become PowerShell parameters, single-quoted with the quote-
// doubling PowerShell requires. Spaces, colons and quotes must survive —
// "$env:USERNAME:(R)" once parsed as a drive and broke icacls.
func TestRenderStageInvocation_QuotesArguments(t *testing.T) {
	got := renderStageInvocation(GuestStage{
		ScriptFile: "virtiofs-mount.ps1",
		Args: map[string]string{
			"Drive": "Z:",
			"Tag":   "dev cell",
			"Odd":   "it's",
		},
	})

	assert.Contains(t, got, `\devcell\stages\virtiofs-mount.ps1'`)
	assert.Contains(t, got, `-Drive 'Z:'`, "a colon must not be re-parsed")
	assert.Contains(t, got, `-Tag 'dev cell'`, "spaces must survive")
	assert.Contains(t, got, `-Odd 'it''s'`, "a single quote is escaped by doubling")
}

// Deterministic ordering: the same stage must render byte-identically every
// time, or golden tests and log diffs become noise.
func TestRenderStageInvocation_IsDeterministic(t *testing.T) {
	st := GuestStage{ScriptFile: "s.ps1", Args: map[string]string{"B": "2", "A": "1", "C": "3"}}
	first := renderStageInvocation(st)
	for i := 0; i < 20; i++ {
		assert.Equal(t, first, renderStageInvocation(st))
	}
	assert.Less(t, strings.Index(first, "-A "), strings.Index(first, "-B "),
		"arguments render in sorted order")
}

// The runner prefers a file-backed stage and falls back to the legacy
// rendered script, so conversion can proceed one stage at a time instead of
// a 17-file big bang (the failure mode the boot-matrix bisect taught).
func TestStagePayload_PrefersTheFileBackedPath(t *testing.T) {
	file := GuestStage{Name: "f", ScriptFile: "wsl2-enable.ps1", Args: map[string]string{"LogName": "001.log"}}
	got := stagePayload(file)
	assert.Contains(t, got, `\devcell\stages\wsl2-enable.ps1'`)
	assert.Contains(t, got, `-LogName '001.log'`)

	legacy := GuestStage{Name: "l", Script: "Write-Output 'legacy'"}
	assert.Equal(t, "Write-Output 'legacy'", stagePayload(legacy),
		"an unconverted stage must still run unchanged")

	// A stage that names a file must not also carry rendered PowerShell.
	assert.NotContains(t, stagePayload(file), "Write-Output")
}
