package main

import (
	"context"
	"fmt"
	"os"
	"os/signal"
	"strconv"
	"syscall"

	_ "github.com/DimmKirr/devcell/docs" // swagger docs (generated by swag init)
	"github.com/DimmKirr/devcell/internal/logger"
	"github.com/DimmKirr/devcell/internal/serve"
	"github.com/spf13/cobra"
)

// @title DevCell Serve API
// @version 1.0
// @description DevCell Serve exposes an OpenAI-compatible HTTP API that proxies chat completion requests to LLM agent binaries running inside a DevCell container.
// @description
// @description ## Why use this?
// @description
// @description Any tool that speaks the OpenAI chat completions protocol (Cursor, Continue, custom scripts, CI pipelines) can target DevCell Serve as its backend. The server routes requests to the appropriate agent binary (Claude Code, OpenCode) based on the `model` field — no SDK or CLI wrapper needed.
// @description
// @description ## Quick start
// @description
// @description 1. Start the server: `cell serve` (or `cell serve --port 9090`)
// @description 2. The server prints an API key on startup. Set `DEVCELL_API_KEY` env var to use a fixed key.
// @description 3. Send requests with `Authorization: Bearer <key>` header.
// @description
// @description ## Model routing
// @description
// @description The `model` field in chat requests selects which agent handles the prompt:
// @description - `"claude"` or `"anthropic"` → routes to the Claude Code CLI
// @description - `"opencode"` → routes to the OpenCode CLI
// @description - `"claude/claude-sonnet-4-5"` → routes to Claude Code with a specific sub-model
// @description
// @description ## Example curl
// @description
// @description ```bash
// @description curl http://localhost:8484/v1/chat/completions \
// @description   -H "Authorization: Bearer $DEVCELL_API_KEY" \
// @description   -H "Content-Type: application/json" \
// @description   -d '{"model":"claude","messages":[{"role":"user","content":"explain this repo"}]}'
// @description ```
// @host localhost:8484
// @BasePath /
// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
// @description Bearer token — set via DEVCELL_API_KEY env var or use the auto-generated key printed on startup. Format: `Bearer dcl-abc123...`

var serveCmd = &cobra.Command{
	Use:   "serve",
	Short: "Start HTTP API server for LLM commands",
	Long: `Starts an OpenAI-compatible HTTP server that proxies chat completions
to LLM agent binaries (claude, opencode).

Endpoints:

    POST /v1/chat/completions  — OpenAI chat completions API
    GET  /v1/models            — list available models
    GET  /healthz              — health check (k8s convention)
    GET  /api/v1/health        — health check (REST convention)
    GET  /api/openapi.json     — OpenAPI spec
    GET  /swagger/             — Swagger UI

The model field selects the agent: "claude", "opencode", or
"claude/claude-sonnet-4-5" (agent/submodel).

Request:

    {"model": "claude", "messages": [{"role": "user", "content": "explain this"}]}

Examples:

    cell serve
    cell serve --port 9090`,
	RunE: runServe,
}

var servePort int

func init() {
	serveCmd.Flags().IntVar(&servePort, "port", serve.DefaultPort, "port to listen on")
}

func runServe(cmd *cobra.Command, args []string) error {
	logLevel := os.Getenv("LOG_LEVEL")
	if logLevel == "" {
		logLevel = "warn"
	}
	logger.Initialize(logLevel, true) // plain text, no colors for server logs

	// Port priority: --port flag > PORT env > default
	if !cmd.Flags().Changed("port") {
		if envPort := os.Getenv("PORT"); envPort != "" {
			if p, err := strconv.Atoi(envPort); err == nil {
				servePort = p
			}
		}
	}

	apiKey := os.Getenv("DEVCELL_API_KEY")
	generated := apiKey == ""
	if generated {
		apiKey = serve.GenerateAPIKey()
	}

	if scanFlag("--dry-run") {
		fmt.Printf("serve: port=%d api_key=%s\n", servePort, apiKey)
		return nil
	}

	ctx, cancel := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer cancel()

	exec := &serve.ShellExecutor{}
	srv := serve.NewServer(exec, servePort)
	srv.SetAPIKey(apiKey)

	addr, errCh := srv.Start(ctx)
	if addr == "" {
		return <-errCh
	}

	fmt.Fprintf(os.Stderr, "devcell serve listening on %s\n", addr)
	if generated {
		fmt.Fprintf(os.Stderr, "API key: %s\n", apiKey)
	}

	return <-errCh
}
